const database = require('./src/config/database').default;

module.exports = [
  {
    name: 'development',
    type: 'mysql',
    host: database.production.host,
    port: 3306,
    username: database.production.username,
    password: database.production.password,
    database: database.production.name,
    synchronize: true,
    logging: false,
    entities: ['src/database/entity/**/*.ts'],
    migrations: ['src/database/migration/**/*.ts'],
    subscribers: ['src/database/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/database/entity',
      migrationsDir: 'src/database/migration',
      subscribersDir: 'src/database/subscriber',
    },
  },
  {
    name: 'production',
    type: 'mysql',
    host: database.production.host,
    port: 3306,
    username: database.production.username,
    password: database.production.password,
    database: database.production.name,
    synchronize: true,
    logging: false,
    entities: ['src/database/entity/**/*.ts'],
    migrations: ['src/database/migration/**/*.ts'],
    subscribers: ['src/database/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/database/entity',
      migrationsDir: 'src/database/migration',
      subscribersDir: 'src/database/subscriber',
    },
  },
  {
    name: 'test',
    type: 'mysql',
    host: database.test.host,
    port: 3306,
    username: database.test.username,
    password: database.test.password,
    database: database.test.name,
    synchronize: true,
    logging: false,
    entities: ['src/database/entity/**/*.ts'],
    migrations: ['src/database/migration/**/*.ts'],
    subscribers: ['src/database/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/database/entity',
      migrationsDir: 'src/database/migration',
      subscribersDir: 'src/database/subscriber',
    },
  },
];
